name: OutlawEconomy
version: 1.0.0
main: com.outlaweco.OutlawEconomyPlugin
api-version: 1.20
authors:
  - OutlawMC
commands:
  balance:
    description: Vérifie ton solde ou consulte celui des autres (admin)
    usage: /balance [joueur|all]
  pay:
    description: Send money to another player
    usage: /pay <player> <amount>
  givemoney:
    description: Donne de l'argent à un joueur (admin)
    usage: /givemoney <player> <amount>
    permission: outlawecoadmin
  removemoney:
    description: Retire de l'argent à un joueur (admin)
    usage: /removemoney <player> <amount>
    permission: outlawecoadmin
  trade:
    description: Start a trade with another player
    usage: /trade <player>
  shop:
    description: Manage and open shops
    usage: /shop <open|create|remove|list>
permissions:
  outlaweco.use:
    description: Allows opening shop templates
    default: false
  outlaweco.command.shopopen:
    description: Allows executing /shop open from chat
    default: false
  outlawecoadmin:
    description: Allows managing shops and templates
    default: op
