name: OutlawEconomy
version: 1.0.0
main: com.outlaweco.OutlawEconomyPlugin
api-version: 1.20
authors:
  - OutlawMC
commands:
  balance:
    description: Check your balance
  pay:
    description: Send money to another player
    usage: /pay <player> <amount>
  trade:
    description: Start a trade with another player
    usage: /trade <player>
  shop:
    description: Ouvrir ou gérer les boutiques
    usage: /shop <open|templates|create|remove|list|add|removeitem|reloadtemplates>
permissions:
  outlaweco.use:
    description: Autorise l'ouverture et l'utilisation des boutiques
    default: true
  outlawecoadmin.use:
    description: Autorise la gestion des PNJ et des templates de boutique
    default: op
