name: OutlawEconomy
version: 1.0.0
main: com.outlaweco.OutlawEconomyPlugin
api-version: 1.20
authors:
  - OutlawMC
commands:
  balance:
    description: Check your balance
    usage: /balance
  pay:
    description: Send money to another player
    usage: /pay <player> <amount>
  trade:
    description: Start a trade with another player
    usage: /trade <player>
  shop:
    description: Manage and open shops
    usage: /shop <open|create|remove|list>
permissions:
  outlaweco.use:
    description: Allows opening shop templates
    default: false
  outlawecoadmin:
    description: Allows managing shops and templates
    default: op
